"""
Active Prevention Engine — Real Enforcement Module
====================================================

Provides REAL prevention capabilities (not advisory/simulated):

Tier 1:
  POST /api/prevention/firewall/execute       Execute generated firewall rules
  (Live capture auto-block integrated into /ws/live_capture)
  (Confidence-gating middleware applied globally)

Tier 2:
  POST /api/prevention/wireless/monitor       Start wireless monitoring (deauth, rogue AP)
  GET  /api/prevention/wireless/status        Wireless monitor status + detected threats
  POST /api/prevention/wireless/stop          Stop wireless monitoring

Tier 3:
  POST /api/prevention/threat-response/enforce   Execute playbook steps for real
  POST /api/prevention/quarantine/{ip}           Network quarantine an IP
  DELETE /api/prevention/quarantine/{ip}         Remove quarantine
  GET  /api/prevention/quarantine               List quarantined IPs
  GET  /api/prevention/circuit-breaker          Drift circuit-breaker status
  POST /api/prevention/circuit-breaker/reset    Reset circuit breaker

Security:
  - All enforcement endpoints require admin role
  - IP validation prevents injection
  - Audit trail for every enforcement action
"""

import asyncio
import datetime
import ipaddress
import logging
import os
import re
import secrets
import shutil
import subprocess
import threading
import time
from collections import deque
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from slowapi import Limiter
from slowapi.util import get_remote_address
from sqlalchemy.orm import Session

from auth import require_auth, require_role
from database import get_db, AuditLog, Incident, IncidentNote

logger = logging.getLogger("robustidps.prevention")

router = APIRouter(prefix="/api/prevention", tags=["Prevention Engine"])
limiter = Limiter(key_func=get_remote_address)


# ══════════════════════════════════════════════════════════════════════════
# TIER 1 — Auto-Execute Firewall Rules
# ══════════════════════════════════════════════════════════════════════════

def _validate_ip(ip: str) -> bool:
    """Validate an IP address to prevent command injection."""
    try:
        ipaddress.ip_address(ip)
        return True
    except ValueError:
        return False


def _validate_ip_or_network(ip: str) -> bool:
    """Validate IP address or CIDR network."""
    try:
        ipaddress.ip_address(ip)
        return True
    except ValueError:
        pass
    try:
        ipaddress.ip_network(ip, strict=False)
        return True
    except ValueError:
        return False


# Track applied rules for rollback
_applied_rules: list[dict] = []
_applied_rules_lock = threading.Lock()


class ExecuteRequest(BaseModel):
    job_id: str = Field(..., description="Job ID with generated rules")
    rule_type: str = Field("iptables", description="iptables or nftables only (snort/suricata are file-based)")
    dry_run: bool = Field(True, description="If True, validate without applying")


class ExecuteResponse(BaseModel):
    executed: int
    failed: int
    dry_run: bool
    results: list[dict]
    rollback_id: str


def _execute_iptables_rule(rule_text: str, dry_run: bool = True) -> dict:
    """Execute a single iptables rule via subprocess."""
    # Only allow iptables -A INPUT rules generated by our system
    if not rule_text.startswith("iptables -A INPUT"):
        return {"rule": rule_text, "status": "skipped", "reason": "Only INPUT chain rules are allowed"}

    # Extract and validate the source IP
    ip_match = re.search(r'-s\s+(\S+)', rule_text)
    if not ip_match or not _validate_ip_or_network(ip_match.group(1)):
        return {"rule": rule_text, "status": "skipped", "reason": "Invalid or missing source IP"}

    if dry_run:
        return {"rule": rule_text, "status": "validated", "reason": "Dry run — rule validated but not applied"}

    try:
        result = subprocess.run(
            rule_text.split(),
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            logger.info("Applied firewall rule: %s", rule_text)
            return {"rule": rule_text, "status": "applied", "reason": "Success"}
        else:
            logger.warning("Failed to apply rule: %s — %s", rule_text, result.stderr.strip())
            return {"rule": rule_text, "status": "failed", "reason": result.stderr.strip()}
    except subprocess.TimeoutExpired:
        return {"rule": rule_text, "status": "failed", "reason": "Timeout"}
    except PermissionError:
        return {"rule": rule_text, "status": "failed", "reason": "Permission denied — container needs NET_ADMIN capability"}
    except FileNotFoundError:
        return {"rule": rule_text, "status": "failed", "reason": "iptables binary not found"}


def _execute_nftables_rule(rule_text: str, dry_run: bool = True) -> dict:
    """Execute a single nftables rule via subprocess."""
    if not rule_text.startswith("nft add rule"):
        return {"rule": rule_text, "status": "skipped", "reason": "Only 'nft add rule' commands are allowed"}

    ip_match = re.search(r'ip saddr\s+(\S+)', rule_text)
    if not ip_match or not _validate_ip_or_network(ip_match.group(1)):
        return {"rule": rule_text, "status": "skipped", "reason": "Invalid or missing source IP"}

    if dry_run:
        return {"rule": rule_text, "status": "validated", "reason": "Dry run — rule validated but not applied"}

    try:
        result = subprocess.run(
            ["nft"] + rule_text[4:].split(),  # strip "nft " prefix
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            logger.info("Applied nftables rule: %s", rule_text)
            return {"rule": rule_text, "status": "applied", "reason": "Success"}
        else:
            return {"rule": rule_text, "status": "failed", "reason": result.stderr.strip()}
    except (subprocess.TimeoutExpired, PermissionError, FileNotFoundError) as e:
        return {"rule": rule_text, "status": "failed", "reason": str(e)}


@router.post("/firewall/execute", response_model=ExecuteResponse)
def execute_firewall_rules(
    body: ExecuteRequest,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """
    Execute previously generated firewall rules (admin only).

    By default runs in dry_run=True mode (validates without applying).
    Set dry_run=False to actually apply rules to the host.
    Requires NET_ADMIN capability in the container.
    """
    from database import FirewallRule
    rules = (
        db.query(FirewallRule)
        .filter(FirewallRule.job_id == body.job_id)
        .all()
    )
    if not rules:
        raise HTTPException(404, f"No generated rules found for job {body.job_id}")

    if body.rule_type not in ("iptables", "nftables"):
        raise HTTPException(400, "Only iptables and nftables can be executed directly. Snort/Suricata rules are file-based.")

    executor = _execute_iptables_rule if body.rule_type == "iptables" else _execute_nftables_rule
    results = []
    executed = 0
    failed = 0
    rollback_id = secrets.token_hex(6)

    for rule in rules:
        if rule.rule_type != body.rule_type:
            continue
        res = executor(rule.rule_text, dry_run=body.dry_run)
        results.append(res)
        if res["status"] == "applied":
            executed += 1
            with _applied_rules_lock:
                _applied_rules.append({
                    "rollback_id": rollback_id,
                    "rule_text": rule.rule_text,
                    "rule_type": body.rule_type,
                    "source_ip": rule.source_ip,
                    "applied_at": datetime.datetime.utcnow().isoformat(),
                    "applied_by": user.email,
                })
        elif res["status"] == "failed":
            failed += 1

    # Audit log
    _log_audit(db, user, "FIREWALL_EXECUTE",
               f"job={body.job_id} type={body.rule_type} dry_run={body.dry_run} "
               f"executed={executed} failed={failed}")

    logger.info(
        "Firewall execute: job=%s type=%s dry_run=%s executed=%d failed=%d user=%s",
        body.job_id, body.rule_type, body.dry_run, executed, failed, user.email,
    )

    return ExecuteResponse(
        executed=executed, failed=failed, dry_run=body.dry_run,
        results=results, rollback_id=rollback_id,
    )


@router.post("/firewall/rollback/{rollback_id}")
def rollback_firewall_rules(
    rollback_id: str,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Rollback previously applied firewall rules by deleting them."""
    with _applied_rules_lock:
        to_rollback = [r for r in _applied_rules if r["rollback_id"] == rollback_id]

    if not to_rollback:
        raise HTTPException(404, f"No rules found for rollback ID {rollback_id}")

    results = []
    for entry in to_rollback:
        # Convert -A (append) to -D (delete) for rollback
        rule_text = entry["rule_text"]
        if entry["rule_type"] == "iptables":
            delete_cmd = rule_text.replace("iptables -A ", "iptables -D ", 1)
            try:
                result = subprocess.run(delete_cmd.split(), capture_output=True, text=True, timeout=10)
                status = "rolled_back" if result.returncode == 0 else "rollback_failed"
                results.append({"rule": rule_text, "status": status, "detail": result.stderr.strip()})
            except Exception as e:
                results.append({"rule": rule_text, "status": "rollback_failed", "detail": str(e)})

    with _applied_rules_lock:
        _applied_rules[:] = [r for r in _applied_rules if r["rollback_id"] != rollback_id]

    _log_audit(db, user, "FIREWALL_ROLLBACK", f"rollback_id={rollback_id} count={len(to_rollback)}")

    return {"rollback_id": rollback_id, "rolled_back": len(results), "results": results}


# ══════════════════════════════════════════════════════════════════════════
# TIER 1 — Live Capture Auto-Block
# ══════════════════════════════════════════════════════════════════════════

# Auto-block configuration (used by /ws/live_capture in main.py)
_auto_block_config = {
    "enabled": False,
    "min_severity": "critical",      # critical | high
    "min_confidence": 0.90,
    "rule_type": "iptables",
    "action": "DROP",
    "max_blocks_per_cycle": 10,      # safety cap per capture cycle
    "blocked_ips": set(),            # track what we've blocked
    "block_log": deque(maxlen=500),  # recent block events
}
_auto_block_lock = threading.Lock()


class AutoBlockConfig(BaseModel):
    enabled: bool = Field(False, description="Enable automatic blocking of high-severity threats")
    min_severity: str = Field("critical", description="Minimum severity to auto-block: critical or high")
    min_confidence: float = Field(0.90, ge=0.5, le=1.0, description="Minimum confidence threshold")
    rule_type: str = Field("iptables", description="iptables or nftables")
    action: str = Field("DROP", description="DROP or REJECT")
    max_blocks_per_cycle: int = Field(10, ge=1, le=100, description="Max IPs to block per capture cycle")


@router.post("/auto-block/configure")
def configure_auto_block(
    body: AutoBlockConfig,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Configure the live-capture auto-block engine (admin only)."""
    if body.min_severity not in ("critical", "high"):
        raise HTTPException(400, "min_severity must be 'critical' or 'high'")
    if body.rule_type not in ("iptables", "nftables"):
        raise HTTPException(400, "rule_type must be 'iptables' or 'nftables'")

    with _auto_block_lock:
        _auto_block_config.update({
            "enabled": body.enabled,
            "min_severity": body.min_severity,
            "min_confidence": body.min_confidence,
            "rule_type": body.rule_type,
            "action": body.action,
            "max_blocks_per_cycle": body.max_blocks_per_cycle,
        })

    _log_audit(db, user, "AUTO_BLOCK_CONFIGURE", f"enabled={body.enabled} severity={body.min_severity}")
    return {"status": "configured", **body.dict()}


@router.get("/auto-block/status")
def auto_block_status(user=Depends(require_auth)):
    """Get auto-block engine status and recent blocks."""
    with _auto_block_lock:
        return {
            "enabled": _auto_block_config["enabled"],
            "min_severity": _auto_block_config["min_severity"],
            "min_confidence": _auto_block_config["min_confidence"],
            "rule_type": _auto_block_config["rule_type"],
            "action": _auto_block_config["action"],
            "total_blocked": len(_auto_block_config["blocked_ips"]),
            "blocked_ips": sorted(_auto_block_config["blocked_ips"]),
            "recent_blocks": list(_auto_block_config["block_log"])[-20:],
        }


def auto_block_check(src_ip: str, label: str, confidence: float, severity: str) -> Optional[dict]:
    """
    Called by /ws/live_capture to auto-block a detected threat.
    Returns block result dict if blocked, None if not.
    """
    with _auto_block_lock:
        if not _auto_block_config["enabled"]:
            return None
        if severity == "benign":
            return None

        sev_order = {"low": 1, "medium": 2, "high": 3, "critical": 4}
        min_sev = sev_order.get(_auto_block_config["min_severity"], 4)
        if sev_order.get(severity, 0) < min_sev:
            return None
        if confidence < _auto_block_config["min_confidence"]:
            return None
        if src_ip in _auto_block_config["blocked_ips"]:
            return None
        if not _validate_ip(src_ip):
            return None

        # Apply block
        rule_type = _auto_block_config["rule_type"]
        action = _auto_block_config["action"]
        if rule_type == "iptables":
            rule_text = f'iptables -A INPUT -s {src_ip} -j {action} -m comment --comment "RobustIDPS-AutoBlock: {label}"'
        else:
            act = "drop" if action == "DROP" else "reject"
            rule_text = f'nft add rule inet filter input ip saddr {src_ip} {act} comment "RobustIDPS-AutoBlock: {label}"'

        executor = _execute_iptables_rule if rule_type == "iptables" else _execute_nftables_rule
        result = executor(rule_text, dry_run=False)

        if result["status"] == "applied":
            _auto_block_config["blocked_ips"].add(src_ip)

        block_event = {
            "src_ip": src_ip,
            "label": label,
            "confidence": round(confidence, 4),
            "severity": severity,
            "rule_type": rule_type,
            "status": result["status"],
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }
        _auto_block_config["block_log"].append(block_event)
        logger.info("Auto-block: %s → %s (%s, conf=%.2f)", src_ip, result["status"], label, confidence)
        return block_event


# ══════════════════════════════════════════════════════════════════════════
# TIER 1 — Confidence-Gated Prediction Rejection
# ══════════════════════════════════════════════════════════════════════════

_confidence_gate = {
    "enabled": False,
    "min_confidence": 0.70,
    "action": "flag",  # flag | reject | hold
    "flagged_count": 0,
    "rejected_count": 0,
}
_confidence_gate_lock = threading.Lock()


class ConfidenceGateConfig(BaseModel):
    enabled: bool = Field(False, description="Enable confidence gating")
    min_confidence: float = Field(0.70, ge=0.1, le=0.99, description="Minimum confidence threshold")
    action: str = Field("flag", description="flag (add warning), reject (return 422), or hold (queue for review)")


@router.post("/confidence-gate/configure")
def configure_confidence_gate(
    body: ConfidenceGateConfig,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Configure the confidence-gating middleware (admin only)."""
    if body.action not in ("flag", "reject", "hold"):
        raise HTTPException(400, "action must be 'flag', 'reject', or 'hold'")

    with _confidence_gate_lock:
        _confidence_gate.update({
            "enabled": body.enabled,
            "min_confidence": body.min_confidence,
            "action": body.action,
        })

    _log_audit(db, user, "CONFIDENCE_GATE_CONFIGURE", f"enabled={body.enabled} min={body.min_confidence}")
    return {"status": "configured", **body.dict()}


@router.get("/confidence-gate/status")
def confidence_gate_status(user=Depends(require_auth)):
    """Get confidence gate status."""
    with _confidence_gate_lock:
        return dict(_confidence_gate)


def check_confidence_gate(predictions: dict) -> dict:
    """
    Apply confidence gating to prediction results.
    Called by prediction endpoints in main.py.
    Returns modified predictions dict with gate status.
    """
    with _confidence_gate_lock:
        if not _confidence_gate["enabled"]:
            return predictions

        min_conf = _confidence_gate["min_confidence"]
        action = _confidence_gate["action"]

    confidence_values = predictions.get("confidence_scores", [])
    if not confidence_values and "predictions" in predictions:
        return predictions  # no per-prediction confidence

    low_confidence_count = sum(1 for c in confidence_values if c < min_conf)
    total = len(confidence_values) if confidence_values else 1
    low_pct = low_confidence_count / total if total > 0 else 0

    gate_result = {
        "confidence_gate_active": True,
        "min_confidence_threshold": min_conf,
        "low_confidence_predictions": low_confidence_count,
        "low_confidence_percentage": round(low_pct * 100, 1),
        "gate_action": action,
    }

    if low_confidence_count > 0:
        with _confidence_gate_lock:
            _confidence_gate["flagged_count"] += low_confidence_count

        if action == "flag":
            gate_result["warning"] = (
                f"{low_confidence_count} predictions below {min_conf} confidence — "
                "flagged for human review"
            )
        elif action == "reject":
            with _confidence_gate_lock:
                _confidence_gate["rejected_count"] += low_confidence_count
            gate_result["warning"] = (
                f"{low_confidence_count} predictions rejected (below {min_conf} confidence)"
            )

    predictions["confidence_gate"] = gate_result
    return predictions


# ══════════════════════════════════════════════════════════════════════════
# TIER 2 — Wireless Monitoring (Deauth / Rogue AP / Evil Twin Detection)
# ══════════════════════════════════════════════════════════════════════════

_wireless_monitor = {
    "running": False,
    "interface": None,
    "thread": None,
    "stop_event": None,
    "known_aps": {},         # BSSID → {ssid, channel, first_seen, last_seen}
    "ap_whitelist": set(),   # whitelisted BSSIDs
    "deauth_events": deque(maxlen=1000),
    "rogue_aps": [],
    "evil_twins": [],
    "stats": {
        "total_deauth_frames": 0,
        "total_deauth_floods": 0,
        "total_rogue_aps": 0,
        "total_evil_twins": 0,
        "started_at": None,
    },
}
_wireless_lock = threading.Lock()


class WirelessMonitorRequest(BaseModel):
    interface: str = Field("wlan1", description="Wireless interface in monitor mode (e.g., wlan1, wlan1mon)")
    deauth_threshold: int = Field(10, ge=3, le=100, description="Deauth frames/sec to flag as flood")
    scan_interval: int = Field(30, ge=5, le=300, description="AP scan interval in seconds")
    ap_whitelist: list[str] = Field(default_factory=list, description="Whitelisted BSSIDs (known-good APs)")


def _wireless_monitor_loop(interface: str, deauth_threshold: int, scan_interval: int, stop_event: threading.Event):
    """Background thread for wireless monitoring using scapy."""
    try:
        from scapy.all import sniff, Dot11, Dot11Deauth, Dot11Beacon, Dot11ProbeResp
    except ImportError:
        logger.error("scapy not installed — wireless monitoring unavailable")
        with _wireless_lock:
            _wireless_monitor["running"] = False
        return

    deauth_counter: dict[str, list[float]] = {}  # src_mac → [timestamps]

    def packet_handler(pkt):
        if stop_event.is_set():
            return

        # Deauth detection
        if pkt.haslayer(Dot11Deauth):
            src = pkt[Dot11].addr2 or "unknown"
            now = time.time()
            if src not in deauth_counter:
                deauth_counter[src] = []
            deauth_counter[src].append(now)
            # Prune old entries (>1s)
            deauth_counter[src] = [t for t in deauth_counter[src] if now - t < 1.0]

            with _wireless_lock:
                _wireless_monitor["stats"]["total_deauth_frames"] += 1

                if len(deauth_counter[src]) >= deauth_threshold:
                    _wireless_monitor["stats"]["total_deauth_floods"] += 1
                    event = {
                        "type": "deauth_flood",
                        "src_mac": src,
                        "dst_mac": pkt[Dot11].addr1 or "broadcast",
                        "frames_per_sec": len(deauth_counter[src]),
                        "severity": "critical",
                        "timestamp": datetime.datetime.utcnow().isoformat(),
                    }
                    _wireless_monitor["deauth_events"].append(event)
                    logger.warning("Deauth flood detected from %s (%d frames/s)", src, len(deauth_counter[src]))
                    deauth_counter[src] = []  # reset after alert

        # Beacon / AP detection
        if pkt.haslayer(Dot11Beacon) or pkt.haslayer(Dot11ProbeResp):
            bssid = pkt[Dot11].addr3
            if not bssid:
                return

            try:
                ssid = pkt[Dot11].info.decode("utf-8", errors="ignore") if pkt[Dot11].info else ""
            except Exception:
                ssid = ""

            channel = None
            try:
                from scapy.all import Dot11Elt
                elt = pkt[Dot11Elt]
                while elt:
                    if elt.ID == 3:  # DS Parameter Set
                        channel = int.from_bytes(elt.info[:1], "little")
                        break
                    elt = elt.payload if hasattr(elt, "payload") and isinstance(elt.payload, Dot11Elt) else None
            except Exception:
                pass

            now = datetime.datetime.utcnow().isoformat()

            with _wireless_lock:
                if bssid in _wireless_monitor["known_aps"]:
                    _wireless_monitor["known_aps"][bssid]["last_seen"] = now
                    if ssid:
                        _wireless_monitor["known_aps"][bssid]["ssid"] = ssid
                else:
                    _wireless_monitor["known_aps"][bssid] = {
                        "ssid": ssid, "channel": channel,
                        "first_seen": now, "last_seen": now,
                    }

                    # Rogue AP detection
                    if bssid not in _wireless_monitor["ap_whitelist"]:
                        rogue = {
                            "type": "rogue_ap",
                            "bssid": bssid, "ssid": ssid, "channel": channel,
                            "severity": "high",
                            "timestamp": now,
                        }
                        _wireless_monitor["rogue_aps"].append(rogue)
                        _wireless_monitor["stats"]["total_rogue_aps"] += 1
                        logger.warning("Rogue AP detected: BSSID=%s SSID=%s", bssid, ssid)

                # Evil twin detection (same SSID, different BSSID)
                if ssid:
                    matching = [
                        (b, info) for b, info in _wireless_monitor["known_aps"].items()
                        if info["ssid"] == ssid and b != bssid
                    ]
                    if matching and bssid not in _wireless_monitor["ap_whitelist"]:
                        existing_bssid = matching[0][0]
                        twin = {
                            "type": "evil_twin",
                            "ssid": ssid,
                            "original_bssid": existing_bssid,
                            "rogue_bssid": bssid,
                            "channel": channel,
                            "severity": "critical",
                            "timestamp": now,
                        }
                        # Avoid duplicate alerts
                        existing_twins = {(t["ssid"], t["rogue_bssid"]) for t in _wireless_monitor["evil_twins"]}
                        if (ssid, bssid) not in existing_twins:
                            _wireless_monitor["evil_twins"].append(twin)
                            _wireless_monitor["stats"]["total_evil_twins"] += 1
                            logger.warning("Evil twin detected: SSID=%s rogue_bssid=%s", ssid, bssid)

    logger.info("Wireless monitor started on %s", interface)
    while not stop_event.is_set():
        try:
            sniff(iface=interface, prn=packet_handler, timeout=scan_interval, store=0)
        except PermissionError:
            logger.error("Permission denied on %s — need root or NET_ADMIN + NET_RAW", interface)
            break
        except Exception as e:
            logger.error("Wireless monitor error: %s", e)
            time.sleep(5)

    with _wireless_lock:
        _wireless_monitor["running"] = False
    logger.info("Wireless monitor stopped on %s", interface)


@router.post("/wireless/monitor")
def start_wireless_monitor(
    body: WirelessMonitorRequest,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Start wireless monitoring for deauth attacks, rogue APs, and evil twins (admin only)."""
    with _wireless_lock:
        if _wireless_monitor["running"]:
            raise HTTPException(409, "Wireless monitor is already running")

        _wireless_monitor["ap_whitelist"] = set(body.ap_whitelist)
        _wireless_monitor["running"] = True
        _wireless_monitor["interface"] = body.interface
        _wireless_monitor["stats"]["started_at"] = datetime.datetime.utcnow().isoformat()

        stop_event = threading.Event()
        _wireless_monitor["stop_event"] = stop_event

        thread = threading.Thread(
            target=_wireless_monitor_loop,
            args=(body.interface, body.deauth_threshold, body.scan_interval, stop_event),
            daemon=True,
        )
        _wireless_monitor["thread"] = thread
        thread.start()

    _log_audit(db, user, "WIRELESS_MONITOR_START", f"interface={body.interface}")
    return {
        "status": "started",
        "interface": body.interface,
        "deauth_threshold": body.deauth_threshold,
        "scan_interval": body.scan_interval,
        "whitelisted_aps": len(body.ap_whitelist),
    }


@router.post("/wireless/stop")
def stop_wireless_monitor(
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Stop the wireless monitor."""
    with _wireless_lock:
        if not _wireless_monitor["running"]:
            raise HTTPException(400, "Wireless monitor is not running")
        if _wireless_monitor["stop_event"]:
            _wireless_monitor["stop_event"].set()
        _wireless_monitor["running"] = False

    _log_audit(db, user, "WIRELESS_MONITOR_STOP", "")
    return {"status": "stopped"}


@router.get("/wireless/status")
def wireless_monitor_status(user=Depends(require_auth)):
    """Get wireless monitor status, detected threats, and known APs."""
    with _wireless_lock:
        return {
            "running": _wireless_monitor["running"],
            "interface": _wireless_monitor["interface"],
            "stats": dict(_wireless_monitor["stats"]),
            "known_aps": dict(_wireless_monitor["known_aps"]),
            "whitelisted_aps": sorted(_wireless_monitor["ap_whitelist"]),
            "rogue_aps": list(_wireless_monitor["rogue_aps"])[-50:],
            "evil_twins": list(_wireless_monitor["evil_twins"])[-50:],
            "recent_deauth_events": list(_wireless_monitor["deauth_events"])[-30:],
        }


@router.post("/wireless/whitelist")
def update_ap_whitelist(
    bssids: list[str],
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Update the AP whitelist (known-good BSSIDs)."""
    with _wireless_lock:
        _wireless_monitor["ap_whitelist"] = set(bssids)
        # Remove whitelisted from rogue list
        _wireless_monitor["rogue_aps"] = [
            ap for ap in _wireless_monitor["rogue_aps"]
            if ap["bssid"] not in _wireless_monitor["ap_whitelist"]
        ]
    _log_audit(db, user, "WIRELESS_WHITELIST_UPDATE", f"count={len(bssids)}")
    return {"whitelisted": len(bssids)}


# ══════════════════════════════════════════════════════════════════════════
# TIER 3 — Inline Threat Response Orchestrator (Enforce Mode)
# ══════════════════════════════════════════════════════════════════════════

class EnforceRequest(BaseModel):
    playbook_id: str = Field(..., description="Playbook to execute")
    source_ip: str = Field(..., description="Threat source IP")
    target_ip: str = Field("", description="Target IP (optional)")
    threat_label: str = Field("", description="Detected threat class")
    confidence: float = Field(0.95, ge=0.0, le=1.0)
    confirm: bool = Field(False, description="Must be True to actually execute — safety gate")


# Step executors — real actions mapped to playbook step types
def _step_rate_limit(src_ip: str, **kwargs) -> dict:
    """Apply rate limiting via iptables hashlimit."""
    if not _validate_ip(src_ip):
        return {"status": "skipped", "reason": "Invalid IP"}
    rule = (
        f"iptables -A INPUT -s {src_ip} -m hashlimit --hashlimit-above 50/sec "
        f'--hashlimit-name ridps_ratelimit -j DROP -m comment --comment "RobustIDPS-RateLimit"'
    )
    try:
        result = subprocess.run(rule.split(), capture_output=True, text=True, timeout=10)
        return {"status": "applied" if result.returncode == 0 else "failed", "detail": result.stderr.strip()}
    except Exception as e:
        return {"status": "failed", "detail": str(e)}


def _step_firewall(src_ip: str, action: str = "DROP", **kwargs) -> dict:
    """Apply iptables DROP/REJECT rule."""
    if not _validate_ip(src_ip):
        return {"status": "skipped", "reason": "Invalid IP"}
    rule = f'iptables -A INPUT -s {src_ip} -j {action} -m comment --comment "RobustIDPS-Enforce"'
    try:
        result = subprocess.run(rule.split(), capture_output=True, text=True, timeout=10)
        return {"status": "applied" if result.returncode == 0 else "failed", "detail": result.stderr.strip()}
    except Exception as e:
        return {"status": "failed", "detail": str(e)}


def _step_block_temp(src_ip: str, duration_min: int = 30, **kwargs) -> dict:
    """Temporary IP block with at-scheduled removal."""
    result = _step_firewall(src_ip, "DROP")
    if result["status"] == "applied":
        # Schedule removal (best-effort)
        try:
            remove_cmd = f'iptables -D INPUT -s {src_ip} -j DROP -m comment --comment "RobustIDPS-Enforce"'
            at_cmd = f'echo "{remove_cmd}" | at now + {duration_min} minutes'
            subprocess.run(["bash", "-c", at_cmd], capture_output=True, timeout=5)
            result["auto_expire_min"] = duration_min
        except Exception:
            result["auto_expire_min"] = None
            result["note"] = "Rule applied but auto-expire failed; manual removal needed"
    return result


def _step_alert_siem(src_ip: str, label: str, confidence: float, **kwargs) -> dict:
    """Forward alert to configured SIEM connectors."""
    try:
        from siem_connectors import emit_event
        event = {
            "threat_label": label,
            "severity": "critical",
            "src_ip": src_ip,
            "confidence": confidence,
            "model_used": "enforcement",
            "action_taken": "enforce",
        }
        emit_event(event)
        return {"status": "sent", "detail": "Alert forwarded to SIEM"}
    except Exception as e:
        return {"status": "failed", "detail": str(e)}


def _step_log(**kwargs) -> dict:
    """Log step — always succeeds."""
    return {"status": "logged"}


# Map step action names to executors
_STEP_EXECUTORS = {
    "rate_limit": _step_rate_limit,
    "firewall": _step_firewall,
    "block_temp": _step_block_temp,
    "block_perm": lambda src_ip, **kw: _step_firewall(src_ip, "DROP"),
    "block_c2": lambda src_ip, **kw: _step_firewall(src_ip, "DROP"),
    "alert": _step_alert_siem,
    "log": _step_log,
    "detect": lambda **kw: {"status": "detected"},
    "verify": lambda **kw: {"status": "verified"},
}


@router.post("/threat-response/enforce")
def enforce_playbook(
    body: EnforceRequest,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """
    Execute a threat response playbook with REAL enforcement actions (admin only).

    Set confirm=True to actually execute. Without confirm=True, returns
    a preview of what would be executed.
    """
    from threat_response import PLAYBOOKS, _get_all_playbooks

    all_pb = _get_all_playbooks(db)
    if body.playbook_id not in all_pb:
        raise HTTPException(404, f"Playbook not found: {body.playbook_id}")

    pb = all_pb[body.playbook_id]

    if not _validate_ip(body.source_ip):
        raise HTTPException(400, "Invalid source IP address")

    response_chain = pb.get("response_chain", [])
    threat_label = body.threat_label or (pb.get("trigger_classes", ["Unknown"])[0])

    if not body.confirm:
        # Preview mode
        preview_steps = []
        for step in response_chain:
            action = step.get("action", "")
            has_executor = action in _STEP_EXECUTORS
            preview_steps.append({
                **step,
                "can_enforce": has_executor,
                "enforcement_type": "real" if has_executor and action not in ("detect", "verify", "log") else "informational",
            })
        return {
            "mode": "preview",
            "playbook": pb["name"],
            "source_ip": body.source_ip,
            "steps": preview_steps,
            "warning": "Set confirm=True to execute these actions for real",
        }

    # Enforce mode — actually execute steps
    incident_id = f"ENF-{secrets.token_hex(4).upper()}"
    steps_executed = []

    for step in response_chain:
        action = step.get("action", "")
        executor = _STEP_EXECUTORS.get(action)

        if executor:
            result = executor(
                src_ip=body.source_ip,
                label=threat_label,
                confidence=body.confidence,
                action="DROP",
            )
            steps_executed.append({
                **step,
                "mode": "enforced",
                "result": result,
                "timestamp": datetime.datetime.utcnow().isoformat(),
            })
        else:
            steps_executed.append({
                **step,
                "mode": "skipped",
                "result": {"status": "no_executor", "detail": f"No real executor for action '{action}'"},
                "timestamp": datetime.datetime.utcnow().isoformat(),
            })

    # Persist incident
    inc = Incident(
        incident_id=incident_id,
        playbook_id=body.playbook_id,
        playbook_name=pb["name"],
        severity=pb.get("severity", "high"),
        source_ip=body.source_ip,
        target_ip=body.target_ip,
        threat_label=threat_label,
        confidence=body.confidence,
        mode="enforced",
        steps=steps_executed,
        total_simulated_ms=0,
        actual_execution_ms=0,
        effectiveness_score=pb.get("effectiveness_score", 0),
        false_positive_rate=pb.get("false_positive_rate", 0),
        triggered_by=user.email,
    )
    db.add(inc)
    db.commit()

    _log_audit(db, user, "THREAT_RESPONSE_ENFORCE",
               f"playbook={body.playbook_id} src_ip={body.source_ip} incident={incident_id}")

    return {
        "incident_id": incident_id,
        "mode": "enforced",
        "playbook": pb["name"],
        "source_ip": body.source_ip,
        "steps": steps_executed,
    }


# ══════════════════════════════════════════════════════════════════════════
# TIER 3 — Drift-Gated Model Circuit Breaker
# ══════════════════════════════════════════════════════════════════════════

_circuit_breaker = {
    "tripped": False,
    "trip_reason": "",
    "tripped_at": None,
    "tripped_by": None,
    "drift_score": 0.0,
    "drift_threshold": 0.30,       # aggregate drift score threshold
    "auto_trip": False,            # if True, prediction endpoints check drift before serving
    "predictions_blocked": 0,
}
_circuit_breaker_lock = threading.Lock()


@router.get("/circuit-breaker")
def circuit_breaker_status(user=Depends(require_auth)):
    """Get the model circuit breaker status."""
    with _circuit_breaker_lock:
        return dict(_circuit_breaker)


@router.post("/circuit-breaker/configure")
def configure_circuit_breaker(
    drift_threshold: float = 0.30,
    auto_trip: bool = False,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Configure the drift-based circuit breaker (admin only)."""
    with _circuit_breaker_lock:
        _circuit_breaker["drift_threshold"] = drift_threshold
        _circuit_breaker["auto_trip"] = auto_trip

    _log_audit(db, user, "CIRCUIT_BREAKER_CONFIGURE", f"threshold={drift_threshold} auto={auto_trip}")
    return {"status": "configured", "drift_threshold": drift_threshold, "auto_trip": auto_trip}


@router.post("/circuit-breaker/trip")
def trip_circuit_breaker(
    reason: str = "Manual trip by admin",
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Manually trip the circuit breaker to stop all predictions (admin only)."""
    with _circuit_breaker_lock:
        _circuit_breaker["tripped"] = True
        _circuit_breaker["trip_reason"] = reason
        _circuit_breaker["tripped_at"] = datetime.datetime.utcnow().isoformat()
        _circuit_breaker["tripped_by"] = user.email

    _log_audit(db, user, "CIRCUIT_BREAKER_TRIP", reason)
    return {"status": "tripped", "reason": reason}


@router.post("/circuit-breaker/reset")
def reset_circuit_breaker(
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Reset the circuit breaker to allow predictions again (admin only)."""
    with _circuit_breaker_lock:
        _circuit_breaker["tripped"] = False
        _circuit_breaker["trip_reason"] = ""
        _circuit_breaker["tripped_at"] = None
        _circuit_breaker["tripped_by"] = None
        _circuit_breaker["predictions_blocked"] = 0

    _log_audit(db, user, "CIRCUIT_BREAKER_RESET", "")
    return {"status": "reset"}


def check_circuit_breaker() -> Optional[str]:
    """
    Called by prediction endpoints. Returns error message if tripped, None if OK.
    """
    with _circuit_breaker_lock:
        if _circuit_breaker["tripped"]:
            _circuit_breaker["predictions_blocked"] += 1
            return (
                f"Model circuit breaker is TRIPPED: {_circuit_breaker['trip_reason']}. "
                f"Predictions are halted until an admin resets the circuit breaker. "
                f"({_circuit_breaker['predictions_blocked']} predictions blocked)"
            )
    return None


def update_drift_score(aggregate_drift_score: float):
    """
    Called by drift detection after analysis.
    Auto-trips the circuit breaker if drift exceeds threshold.
    """
    with _circuit_breaker_lock:
        _circuit_breaker["drift_score"] = aggregate_drift_score
        if _circuit_breaker["auto_trip"] and aggregate_drift_score > _circuit_breaker["drift_threshold"]:
            if not _circuit_breaker["tripped"]:
                _circuit_breaker["tripped"] = True
                _circuit_breaker["trip_reason"] = (
                    f"Auto-tripped: aggregate drift score {aggregate_drift_score:.4f} "
                    f"exceeds threshold {_circuit_breaker['drift_threshold']}"
                )
                _circuit_breaker["tripped_at"] = datetime.datetime.utcnow().isoformat()
                _circuit_breaker["tripped_by"] = "system/auto"
                logger.warning("Circuit breaker AUTO-TRIPPED: drift=%.4f", aggregate_drift_score)


# ══════════════════════════════════════════════════════════════════════════
# TIER 3 — Network Quarantine
# ══════════════════════════════════════════════════════════════════════════

_quarantine: dict[str, dict] = {}  # ip → {reason, quarantined_at, quarantined_by, ttl_min, expires_at}
_quarantine_lock = threading.Lock()


class QuarantineRequest(BaseModel):
    reason: str = Field("Threat detected", description="Reason for quarantine")
    ttl_minutes: int = Field(60, ge=1, le=1440, description="Auto-expire after N minutes (max 24h)")
    bidirectional: bool = Field(True, description="Block both inbound and outbound")


@router.post("/quarantine/{ip}")
def quarantine_ip(
    ip: str,
    body: QuarantineRequest,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Quarantine an IP address — applies bidirectional firewall DROP rules (admin only)."""
    if not _validate_ip(ip):
        raise HTTPException(400, f"Invalid IP address: {ip}")

    with _quarantine_lock:
        if ip in _quarantine:
            raise HTTPException(409, f"IP {ip} is already quarantined")

    # Apply rules
    rules_applied = []
    inbound = f'iptables -A INPUT -s {ip} -j DROP -m comment --comment "RobustIDPS-Quarantine"'
    res_in = _execute_iptables_rule(inbound, dry_run=False)
    rules_applied.append({"direction": "inbound", **res_in})

    if body.bidirectional:
        outbound = f'iptables -A OUTPUT -d {ip} -j DROP -m comment --comment "RobustIDPS-Quarantine"'
        try:
            result = subprocess.run(outbound.split(), capture_output=True, text=True, timeout=10)
            rules_applied.append({
                "direction": "outbound",
                "rule": outbound,
                "status": "applied" if result.returncode == 0 else "failed",
                "reason": result.stderr.strip(),
            })
        except Exception as e:
            rules_applied.append({"direction": "outbound", "rule": outbound, "status": "failed", "reason": str(e)})

    now = datetime.datetime.utcnow()
    expires = now + datetime.timedelta(minutes=body.ttl_minutes)

    with _quarantine_lock:
        _quarantine[ip] = {
            "reason": body.reason,
            "quarantined_at": now.isoformat(),
            "quarantined_by": user.email,
            "ttl_minutes": body.ttl_minutes,
            "expires_at": expires.isoformat(),
            "bidirectional": body.bidirectional,
            "rules_applied": rules_applied,
        }

    _log_audit(db, user, "QUARANTINE_ADD", f"ip={ip} reason={body.reason} ttl={body.ttl_minutes}m")

    return {
        "status": "quarantined",
        "ip": ip,
        "reason": body.reason,
        "expires_at": expires.isoformat(),
        "rules_applied": rules_applied,
    }


@router.delete("/quarantine/{ip}")
def unquarantine_ip(
    ip: str,
    user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
):
    """Remove quarantine from an IP address (admin only)."""
    if not _validate_ip(ip):
        raise HTTPException(400, f"Invalid IP address: {ip}")

    with _quarantine_lock:
        if ip not in _quarantine:
            raise HTTPException(404, f"IP {ip} is not quarantined")
        entry = _quarantine.pop(ip)

    # Remove rules
    results = []
    del_in = f'iptables -D INPUT -s {ip} -j DROP -m comment --comment "RobustIDPS-Quarantine"'
    try:
        r = subprocess.run(del_in.split(), capture_output=True, text=True, timeout=10)
        results.append({"direction": "inbound", "status": "removed" if r.returncode == 0 else "failed"})
    except Exception as e:
        results.append({"direction": "inbound", "status": "failed", "detail": str(e)})

    if entry.get("bidirectional"):
        del_out = f'iptables -D OUTPUT -d {ip} -j DROP -m comment --comment "RobustIDPS-Quarantine"'
        try:
            r = subprocess.run(del_out.split(), capture_output=True, text=True, timeout=10)
            results.append({"direction": "outbound", "status": "removed" if r.returncode == 0 else "failed"})
        except Exception as e:
            results.append({"direction": "outbound", "status": "failed", "detail": str(e)})

    _log_audit(db, user, "QUARANTINE_REMOVE", f"ip={ip}")

    return {"status": "unquarantined", "ip": ip, "results": results}


@router.get("/quarantine")
def list_quarantined(user=Depends(require_auth)):
    """List all quarantined IPs."""
    now = datetime.datetime.utcnow()
    with _quarantine_lock:
        entries = []
        expired = []
        for ip, info in _quarantine.items():
            expires_at = datetime.datetime.fromisoformat(info["expires_at"])
            is_expired = now > expires_at
            entries.append({
                "ip": ip,
                **info,
                "expired": is_expired,
                "remaining_minutes": max(0, int((expires_at - now).total_seconds() / 60)),
            })
            if is_expired:
                expired.append(ip)

    return {
        "quarantined": entries,
        "total": len(entries),
        "expired": len(expired),
    }


# ══════════════════════════════════════════════════════════════════════════
# TIER 3 — Prevention Dashboard (aggregate status)
# ══════════════════════════════════════════════════════════════════════════

@router.get("/dashboard")
def prevention_dashboard(user=Depends(require_auth)):
    """Aggregate prevention engine status across all tiers."""
    with _auto_block_lock:
        auto_block = {
            "enabled": _auto_block_config["enabled"],
            "total_blocked": len(_auto_block_config["blocked_ips"]),
        }

    with _confidence_gate_lock:
        conf_gate = {
            "enabled": _confidence_gate["enabled"],
            "flagged": _confidence_gate["flagged_count"],
            "rejected": _confidence_gate["rejected_count"],
        }

    with _circuit_breaker_lock:
        cb = {
            "tripped": _circuit_breaker["tripped"],
            "drift_score": _circuit_breaker["drift_score"],
            "predictions_blocked": _circuit_breaker["predictions_blocked"],
        }

    with _wireless_lock:
        wireless = {
            "running": _wireless_monitor["running"],
            "deauth_floods": _wireless_monitor["stats"]["total_deauth_floods"],
            "rogue_aps": _wireless_monitor["stats"]["total_rogue_aps"],
            "evil_twins": _wireless_monitor["stats"]["total_evil_twins"],
        }

    with _quarantine_lock:
        quarantine = {"total": len(_quarantine)}

    with _applied_rules_lock:
        firewall = {"rules_applied": len(_applied_rules)}

    return {
        "tier_1": {
            "auto_block": auto_block,
            "confidence_gate": conf_gate,
            "firewall_execution": firewall,
        },
        "tier_2": {
            "wireless_monitor": wireless,
        },
        "tier_3": {
            "circuit_breaker": cb,
            "quarantine": quarantine,
        },
    }


# ── Audit helper ─────────────────────────────────────────────────────────

def _log_audit(db: Session, user, action: str, details: str):
    """Write an audit log entry for prevention actions."""
    try:
        log = AuditLog(
            user_id=user.id if user else None,
            action=action,
            resource="prevention",
            details=details,
            ip_address="",
            user_agent="prevention-engine",
        )
        db.add(log)
        db.commit()
    except Exception:
        logger.warning("Failed to write audit log for %s", action)
