#!/usr/bin/env bash
# ============================================================
# SSL Certificate Setup for RobustIDPS.ai
#
# Option 1 (Recommended): Cloudflare Origin CA Certificate
#   - Free, 15-year validity, trusted by Cloudflare
#   - Requires Full (Strict) SSL mode in Cloudflare dashboard
#   - Generate at: Cloudflare Dashboard → SSL/TLS → Origin Server
#   - Save certificate as deploy/ssl/origin.crt
#   - Save private key as deploy/ssl/origin.key
#
# Option 2 (Fallback): Self-signed certificate
#   - Only works with Cloudflare Full mode (not Strict)
#   - Browsers will show "Not Secure" if accessed directly
#   - Auto-generated by this script if no certs exist
#
# Usage: ./deploy/generate-ssl.sh [--self-signed]
# ============================================================
set -euo pipefail

SSL_DIR="$(dirname "$0")/ssl"
mkdir -p "$SSL_DIR"

# Check if Cloudflare Origin CA certs are already in place
if [ -f "$SSL_DIR/origin.crt" ] && [ -f "$SSL_DIR/origin.key" ]; then
    # Verify if it's a Cloudflare Origin CA cert or self-signed
    if openssl x509 -in "$SSL_DIR/origin.crt" -noout -issuer 2>/dev/null | grep -qi "cloudflare"; then
        echo "✓ Cloudflare Origin CA certificate found in $SSL_DIR"
        echo "  This is the recommended setup for Full (Strict) SSL mode."
        openssl x509 -in "$SSL_DIR/origin.crt" -noout -dates 2>/dev/null || true
        exit 0
    else
        echo "⚠ Existing certificate is self-signed (not Cloudflare Origin CA)."
        echo "  Browsers may show 'Not Secure' warnings."
        echo ""
        echo "  To upgrade to Cloudflare Origin CA (recommended):"
        echo "    1. Generate cert at Cloudflare Dashboard → SSL/TLS → Origin Server"
        echo "    2. Save certificate to: $SSL_DIR/origin.crt"
        echo "    3. Save private key to: $SSL_DIR/origin.key"
        echo "    4. Set Cloudflare SSL mode to Full (Strict)"
        echo "    5. Re-run deploy"
        echo ""
        echo "  To regenerate self-signed: rm $SSL_DIR/origin.* && $0 --self-signed"
        exit 0
    fi
fi

# If --self-signed flag is passed, generate self-signed cert
if [ "${1:-}" = "--self-signed" ]; then
    echo "Generating self-signed SSL certificate for robustidps.ai..."
    echo "⚠ WARNING: Self-signed certs cause browser 'Not Secure' warnings."
    echo "  Consider using Cloudflare Origin CA instead."
    echo ""

    openssl req -x509 -nodes -days 3650 \
        -newkey rsa:2048 \
        -keyout "$SSL_DIR/origin.key" \
        -out "$SSL_DIR/origin.crt" \
        -subj "/C=US/ST=State/L=City/O=RobustIDPS/CN=robustidps.ai" \
        -addext "subjectAltName=DNS:robustidps.ai,DNS:www.robustidps.ai,DNS:*.robustidps.ai"

    chmod 600 "$SSL_DIR/origin.key"
    chmod 644 "$SSL_DIR/origin.crt"

    echo "Done! Self-signed certificates generated:"
    echo "  Certificate: $SSL_DIR/origin.crt"
    echo "  Private key: $SSL_DIR/origin.key"
    echo ""
    echo "Set Cloudflare SSL/TLS mode to 'Full' (NOT Full Strict)."
    exit 0
fi

# Default: prompt user to use Cloudflare Origin CA
echo "============================================================"
echo "  SSL Certificate Setup for RobustIDPS.ai"
echo "============================================================"
echo ""
echo "No SSL certificates found. You have two options:"
echo ""
echo "━━━ OPTION 1: Cloudflare Origin CA (Recommended) ━━━"
echo ""
echo "  This eliminates all browser 'Not Secure' warnings."
echo ""
echo "  1. Go to Cloudflare Dashboard → SSL/TLS → Origin Server"
echo "  2. Click 'Create Certificate'"
echo "  3. Keep defaults (RSA 2048, *.robustidps.ai, 15 years)"
echo "  4. Copy the certificate PEM and save as:"
echo "       $SSL_DIR/origin.crt"
echo "  5. Copy the private key PEM and save as:"
echo "       $SSL_DIR/origin.key"
echo "  6. Set SSL/TLS encryption mode to 'Full (Strict)'"
echo "  7. Ensure DNS records are Proxied (orange cloud)"
echo "  8. Re-run this deploy"
echo ""
echo "━━━ OPTION 2: Self-signed (Quick, but shows warnings) ━━━"
echo ""
echo "  Run: $0 --self-signed"
echo ""
echo "============================================================"
exit 1
